if (typeof md == "undefined") var md = {};

md.BaKoMa = Class.define({
    members: {
        init: function () {
            this._fontmap = {
                'cal' : 'cmsy10',
                'rm'  : 'cmr10',
                'tt'  : 'cmtt10', // monospaced
                'it'  : 'cmmi10', // italics
                'bf'  : 'cmb10', // bold face
                'sf'  : 'cmss10', //sans serif
                'ex'  : 'cmex10' // ???extended???
            };
            this._inversemap = {
                'cmsy10' :'cal',
                'cmr10'  :'rm',
                'cmtt10' :'tt',
                'cmmi10' :'it',
                'cmb10'  :'bf',
                'cmss10' :'sf',
                'cmex10' :'ex' 
            };
            this.fontmap = {};
            for (var key in this._fontmap) {
                this.fontmap[key] = new md.TTF("/res/" + this._fontmap[key] + ".ttf");
            }
        },

        getGlyph: function (font, symbol) {
            var entry = md.tex_to_bakoma[symbol];
            if (typeof entry == "undefined") {
                var glyphIndex = this.fontmap[font]['cmap'].getGlyphIndex(symbol);
                if (typeof glyphIndex == "undefined") {
                    console.debug("Error: symbol '" + symbol + "' not fount in font '" + font + "'");
                    return;
                }
                return this.fontmap[font]['glyf'].glyphs[glyphIndex];
            }
            var _font = entry[0];
            var glyphIndex = entry[1];
            glyphIndex -= 2; // XXX: apparently the indiced from the table I "stole" from matplotlib are off by 2...
            return this.fontmap[this._inversemap[_font]]['glyf'].glyphs[glyphIndex];
        }
    }
});

md.tex_to_bakoma = {
    '\\oint'                : ['cmex10',  45],
    '\\bigodot'             : ['cmex10',  50],
    '\\bigoplus'            : ['cmex10',  55],
    '\\bigotimes'           : ['cmex10',  59],
    '\\sum'                 : ['cmex10',  51],
    '\\prod'                : ['cmex10',  24],
    '\\int'                 : ['cmex10',  56],
    '\\bigcup'              : ['cmex10',  28],
    '\\bigcap'              : ['cmex10',  60],
    '\\biguplus'            : ['cmex10',  32],
    '\\bigwedge'            : ['cmex10',   4],
    '\\bigvee'              : ['cmex10',  37],
    '\\coprod'              : ['cmex10',  42],
    '\\__sqrt__'            : ['cmex10',  48],
    '\\leftbrace'           : ['cmex10',  92],
    '{'                    : ['cmex10',  92],
    '\\{'                   : ['cmex10',  92],
    '\\rightbrace'          : ['cmex10', 130],
    '}'                    : ['cmex10', 130],
    '\\}'                   : ['cmex10', 130],
    '\\leftangle'           : ['cmex10',  97],
    '\\rightangle'          : ['cmex10',  64],
    '\\langle'              : ['cmex10',  97],
    '\\rangle'              : ['cmex10',  64],
    '\\widehat'             : ['cmex10',  15],
    '\\widetilde'           : ['cmex10',  52],
    '\\widebar'             : ['cmr10',  131],
    '\\omega'               : ['cmmi10',  29],
    '\\varepsilon'          : ['cmmi10',  20],
    '\\vartheta'            : ['cmmi10',  22],
    '\\varrho'              : ['cmmi10',  61],
    '\\varsigma'            : ['cmmi10',  41],
    '\\varphi'              : ['cmmi10',   6],
    '\\leftharpoonup'       : ['cmmi10', 108],
    '\\leftharpoondown'     : ['cmmi10',  68],
    '\\rightharpoonup'      : ['cmmi10', 117],
    '\\rightharpoondown'    : ['cmmi10',  77],
    '\\triangleright'       : ['cmmi10', 130],
    '\\triangleleft'        : ['cmmi10',  89],
    '.'                    : ['cmmi10',  51],
    ','                    : ['cmmi10',  44],
    '<'                    : ['cmmi10',  99],
    '/'                    : ['cmmi10',  98],
    '>'                    : ['cmmi10', 107],
    '\\flat'                : ['cmmi10', 131],
    '\\natural'             : ['cmmi10',  90],
    '\\sharp'               : ['cmmi10',  50],
    '\\smile'               : ['cmmi10',  97],
    '\\frown'               : ['cmmi10',  58],
    '\\ell'                 : ['cmmi10', 102],
    '\\imath'               : ['cmmi10',   8],
    '\\jmath'               : ['cmmi10',  65],
    '\\wp'                  : ['cmmi10',  14],
    '\\alpha'               : ['cmmi10',  13],
    '\\beta'                : ['cmmi10',  35],
    '\\gamma'               : ['cmmi10',  24],
    '\\delta'               : ['cmmi10',  38],
    '\\epsilon'             : ['cmmi10',  54],
    '\\zeta'                : ['cmmi10',  10],
    '\\eta'                 : ['cmmi10',   5],
    '\\theta'               : ['cmmi10',  18],
    '\\iota'                : ['cmmi10',  28],
    '\\lambda'              : ['cmmi10',   9],
    '\\mu'                  : ['cmmi10',  32],
    '\\nu'                  : ['cmmi10',  34],
    '\\xi'                  : ['cmmi10',   7],
    '\\pi'                  : ['cmmi10',  36],
    '\\kappa'               : ['cmmi10',  30],
    '\\rho'                 : ['cmmi10',  39],
    '\\sigma'               : ['cmmi10',  21],
    '\\tau'                 : ['cmmi10',  43],
    '\\upsilon'             : ['cmmi10',  25],
    '\\phi'                 : ['cmmi10',  42],
    '\\chi'                 : ['cmmi10',  17],
    '\\psi'                 : ['cmmi10',  31],
    '|'                    : ['cmsy10',  47],
    '\\|'                   : ['cmsy10',  47],
    '('                    : ['cmr10',  119],
    '\\leftparen'           : ['cmr10',  119],
    '\\rightparen'          : ['cmr10',   68],
    ')'                    : ['cmr10',   68],
    '+'                    : ['cmr10',   76],
    '0'                    : ['cmr10',   40],
    '1'                    : ['cmr10',  100],
    '2'                    : ['cmr10',   49],
    '3'                    : ['cmr10',  110],
    '4'                    : ['cmr10',   59],
    '5'                    : ['cmr10',  120],
    '6'                    : ['cmr10',   69],
    '7'                    : ['cmr10',  127],
    '8'                    : ['cmr10',   77],
    '9'                    : ['cmr10',   22],
    ':'                    : ['cmr10',   85],
    ';'                    : ['cmr10',   31],
    '='                    : ['cmr10',   41],
    '\\leftbracket'         : ['cmr10',   62],
    '['                    : ['cmr10',   62],
    '\\rightbracket'        : ['cmr10',   72],
    ']'                    : ['cmr10',   72],
    '\\%'                   : ['cmr10',   48],
    '%'                    : ['cmr10',   48],
    '\\$'                   : ['cmr10',   99],
    '@'                    : ['cmr10',  111],
    '\\#'                   : ['cmr10',   39],
    '\\_'                   : ['cmtt10', 79],
    '\\Gamma'               : ['cmr10',  19],
    '\\Delta'               : ['cmr10',   6],
    '\\Theta'               : ['cmr10',   7],
    '\\Lambda'              : ['cmr10',  14],
    '\\Xi'                  : ['cmr10',   3],
    '\\Pi'                  : ['cmr10',  17],
    '\\Sigma'               : ['cmr10',  10],
    '\\Upsilon'             : ['cmr10',  11],
    '\\Phi'                 : ['cmr10',   9],
    '\\Psi'                 : ['cmr10',  15],
    '\\Omega'               : ['cmr10',  12],
    '\\leftarrow'           : ['cmsy10',  10],
    '\\uparrow'             : ['cmsy10',  25],
    '\\downarrow'           : ['cmsy10',  28],
    '\\leftrightarrow'      : ['cmsy10',  24],
    '\\nearrow'             : ['cmsy10',  99],
    '\\searrow'             : ['cmsy10',  57],
    '\\simeq'               : ['cmsy10', 108],
    '\\Leftarrow'           : ['cmsy10', 104],
    '\\Rightarrow'          : ['cmsy10', 112],
    '\\Uparrow'             : ['cmsy10',  60],
    '\\Downarrow'           : ['cmsy10',  68],
    '\\Leftrightarrow'      : ['cmsy10',  51],
    '\\nwarrow'             : ['cmsy10',  65],
    '\\swarrow'             : ['cmsy10', 116],
    '\\propto'              : ['cmsy10',  15],
    '\\prime'               : ['cmsy10',  73],
    "'"                    : ['cmsy10',  73],
    '\\infty'               : ['cmsy10',  32],
    '\\in'                  : ['cmsy10',  59],
    '\\ni'                  : ['cmsy10', 122],
    '\\bigtriangleup'       : ['cmsy10',  80],
    '\\bigtriangledown'     : ['cmsy10', 132],
    '\\slash'               : ['cmsy10',  87],
    '\\forall'              : ['cmsy10',  21],
    '\\exists'              : ['cmsy10',   5],
    '\\neg'                 : ['cmsy10',  20],
    '\\emptyset'            : ['cmsy10',  33],
    '\\Re'                  : ['cmsy10',  95],
    '\\Im'                  : ['cmsy10',  52],
    '\\top'                 : ['cmsy10', 100],
    '\\bot'                 : ['cmsy10',  11],
    '\\aleph'               : ['cmsy10',  26],
    '\\cup'                 : ['cmsy10',   6],
    '\\cap'                 : ['cmsy10',  19],
    '\\uplus'               : ['cmsy10',  58],
    '\\wedge'               : ['cmsy10',  43],
    '\\vee'                 : ['cmsy10',  96],
    '\\vdash'               : ['cmsy10', 109],
    '\\dashv'               : ['cmsy10',  66],
    '\\lfloor'              : ['cmsy10', 117],
    '\\rfloor'              : ['cmsy10',  74],
    '\\lceil'               : ['cmsy10', 123],
    '\\rceil'               : ['cmsy10',  81],
    '\\lbrace'              : ['cmsy10',  92],
    '\\rbrace'              : ['cmsy10', 105],
    '\\mid'                 : ['cmsy10',  47],
    '\\vert'                : ['cmsy10',  47],
    '\\Vert'                : ['cmsy10',  44],
    '\\updownarrow'         : ['cmsy10',  94],
    '\\Updownarrow'         : ['cmsy10',  53],
    '\\backslash'           : ['cmsy10', 126],
    '\\wr'                  : ['cmsy10', 101],
    '\\nabla'               : ['cmsy10', 110],
    '\\sqcup'               : ['cmsy10',  67],
    '\\sqcap'               : ['cmsy10', 118],
    '\\sqsubseteq'          : ['cmsy10',  75],
    '\\sqsupseteq'          : ['cmsy10', 124],
    '\\S'                   : ['cmsy10', 129],
    '\\dag'                 : ['cmsy10',  71],
    '\\ddag'                : ['cmsy10', 127],
    '\\P'                   : ['cmsy10', 130],
    '\\clubsuit'            : ['cmsy10',  18],
    '\\diamondsuit'         : ['cmsy10',  34],
    '\\heartsuit'           : ['cmsy10',  22],
    '-'                    : ['cmsy10',  17],
    '\\cdot'                : ['cmsy10',  78],
    '\\times'               : ['cmsy10',  13],
    '*'                    : ['cmsy10',   9],
    '\\ast'                 : ['cmsy10',   9],
    '\\div'                 : ['cmsy10',  31],
    '\\diamond'             : ['cmsy10',  48],
    '\\pm'                  : ['cmsy10',   8],
    '\\mp'                  : ['cmsy10',  98],
    '\\oplus'               : ['cmsy10',  16],
    '\\ominus'              : ['cmsy10',  56],
    '\\otimes'              : ['cmsy10',  30],
    '\\oslash'              : ['cmsy10', 107],
    '\\odot'                : ['cmsy10',  64],
    '\\bigcirc'             : ['cmsy10', 115],
    '\\circ'                : ['cmsy10',  72],
    '\\bullet'              : ['cmsy10',  84],
    '\\asymp'               : ['cmsy10', 121],
    '\\equiv'               : ['cmsy10',  35],
    '\\subseteq'            : ['cmsy10', 103],
    '\\supseteq'            : ['cmsy10',  42],
    '\\leq'                 : ['cmsy10',  14],
    '\\geq'                 : ['cmsy10',  29],
    '\\preceq'              : ['cmsy10',  79],
    '\\succeq'              : ['cmsy10', 131],
    '\\sim'                 : ['cmsy10',  27],
    '\\approx'              : ['cmsy10',  23],
    '\\subset'              : ['cmsy10',  50],
    '\\supset'              : ['cmsy10',  86],
    '\\ll'                  : ['cmsy10',  85],
    '\\gg'                  : ['cmsy10',  40],
    '\\prec'                : ['cmsy10',  93],
    '\\succ'                : ['cmsy10',  49],
    '\\rightarrow'          : ['cmsy10',  12],
    '\\to'                  : ['cmsy10',  12],
    '\\spadesuit'           : ['cmsy10',   7],
}
